FROM node:22.12-alpine3.20
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install -g node-gyp

RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install

WORKDIR /app

COPY . .

RUN chown -R node:node /app

USER node

RUN ["npm", "run", "build"]

EXPOSE 1337

CMD ["npm", "run", "develop"]

